version : '3'
services:
    core_api:
        build: .
        ports:
            - "8000:8000"
        volumes:
            - ./app/:/app/
    selenium:
        image: selenium/standalone-chrome
        ports:
        - 4444:4444
        restart: always